### ISSUE TITLE
MOD Routing Engine in an Infinite Loop

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#88]
2 things that I'm seeing with https://github.com/opentripplanner/OpenTripPlanner/tree/trimet-dev:

a) the graph doesn't pass it's tests (workaround is mvn package -DskipTests ... but not the best sign)

b) the routing engine intermittently goes nuts and chews up all server resources ... below is the output I've seen:
```
16:46:06.561 INFO (GraphUpdaterConfigurator.java:138) Configured GraphUpdater: org.opentripplanner.updater.bike_rental.BikeRentalUpdater@4e26040f
16:46:06.568 INFO (PollingGraphUpdater.java:63) Polling updater started: org.opentripplanner.updater.traffic.OpenTrafficUpdater@5308e79d
16:46:06.569 ERROR (PollingGraphUpdater.java:78) Error while running polling updater of type opentraffic-updater
java.lang.NullPointerException: null
        at org.opentripplanner.updater.traffic.OpenTrafficUpdater.runPolling(OpenTrafficUpdater.java:45) ~[otp.jar:1.1]
        at org.opentripplanner.updater.PollingGraphUpdater.run(PollingGraphUpdater.java:68) ~[otp.jar:1.1]
        at org.opentripplanner.updater.GraphUpdaterManager$1.run(GraphUpdaterManager.java:148) [otp.jar:1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
16:46:06.569 INFO (OpenTrafficUpdater.java:38) Loading speed data
16:46:06.568 ERROR (GraphUpdaterConfigurator.java:141) Can't configure:
java.lang.IllegalArgumentException: Unknown bike rental source type:
        at org.opentripplanner.updater.bike_park.BikeParkUpdater.configurePolling(BikeParkUpdater.java:95) ~[otp.jar:1.1]
        at org.opentripplanner.updater.PollingGraphUpdater.configure(PollingGraphUpdater.java:99) ~[otp.jar:1.1]
        at org.opentripplanner.updater.GraphUpdaterConfigurator.applyConfigurationToGraph(GraphUpdaterConfigurator.java:134) [otp.jar:1.1]
        at org.opentripplanner.updater.GraphUpdaterConfigurator.setupGraph(GraphUpdaterConfigurator.java:64) [otp.jar:1.1]
        at org.opentripplanner.standalone.Router.startup(Router.java:165) [otp.jar:1.1]
        at org.opentripplanner.routing.impl.InputStreamGraphSource.loadGraph(InputStreamGraphSource.java:236) [otp.jar:1.1]
        at org.opentripplanner.routing.impl.InputStreamGraphSource.reload(InputStreamGraphSource.java:133) [otp.jar:1.1]
        at org.opentripplanner.routing.services.GraphService.registerGraph(GraphService.java:196) [otp.jar:1.1]
        at org.opentripplanner.routing.impl.GraphScanner.startup(GraphScanner.java:86) [otp.jar:1.1]
        at org.opentripplanner.standalone.OTPMain.run(OTPMain.java:135) [otp.jar:1.1]
        at org.opentripplanner.standalone.OTPMain.main(OTPMain.java:86) [otp.jar:1.1]

16:46:06.570 ERROR (GraphUpdaterManager.java:150) Error while running updater org.opentripplanner.updater.traffic.OpenTrafficUpdater:
java.lang.IllegalArgumentException: timeout value is negative
        at java.lang.Thread.sleep(Native Method) [na:1.8.0_92]
        at org.opentripplanner.updater.PollingGraphUpdater.run(PollingGraphUpdater.java:83) ~[otp.jar:1.1]
        at org.opentripplanner.updater.GraphUpdaterManager$1.run(GraphUpdaterManager.java:148) ~[otp.jar:1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
16:46:06.570 ERROR (PollingGraphUpdater.java:78) Error while running polling updater of type opentraffic-updater
java.lang.NullPointerException: null
        at org.opentripplanner.updater.traffic.OpenTrafficUpdater.runPolling(OpenTrafficUpdater.java:45) ~[otp.jar:1.1]
        at org.opentripplanner.updater.PollingGraphUpdater.run(PollingGraphUpdater.java:68) ~[otp.jar:1.1]
        at org.opentripplanner.updater.GraphUpdaterManager$1.run(GraphUpdaterManager.java:148) [otp.jar:1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
16:46:06.571 ERROR (GraphUpdaterManager.java:150) Error while running updater org.opentripplanner.updater.traffic.OpenTrafficUpdater:
java.lang.IllegalArgumentException: timeout value is negative
        at java.lang.Thread.sleep(Native Method) [na:1.8.0_92]
        at org.opentripplanner.updater.PollingGraphUpdater.run(PollingGraphUpdater.java:83) ~[otp.jar:1.1]
        at org.opentripplanner.updater.GraphUpdaterManager$1.run(GraphUpdaterManager.java:148) ~[otp.jar:1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
16:46:06.574 INFO (PollingGraphUpdater.java:63) Polling updater started: Streaming stoptime updater with update source = GtfsRealtimeHttpUpdateStreamer(http://trimet.org/transweb/ws/V1/TripUpdate)
16:46:06.757 INFO (Router.java:173) Computed ellipsoid/geoid offset at (45.23456605, -122.60907094999999) as -19.6427556390466
16:46:06.764 INFO (GrizzlyServer.java:67) Starting OTP Grizzly server on ports 51315 (HTTP) and 51311 (HTTPS) of interface 0.0.0.0
16:46:06.764 INFO (GrizzlyServer.java:69) OTP server base path is /var/otp
16:46:07.325 INFO (GrizzlyServer.java:49) Java reports that this machine has 24 available processors.
16:46:07.325 INFO (GrizzlyServer.java:57) Maximum HTTP handler thread pool size will be 24 threads.
16:46:07.374 ERROR (WebsocketGtfsRealtimeUpdater.java:138) Unknown exception when trying to connect to :
java.lang.NullPointerException: uri.host
        at com.ning.http.client.RequestBuilderBase.setURI(RequestBuilderBase.java:383) ~[otp.jar:1.1]
        at com.ning.http.client.RequestBuilderBase.setUrl(RequestBuilderBase.java:378) ~[otp.jar:1.1]
        at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.setUrl(AsyncHttpClient.java:318) ~[otp.jar:1.1]
        at com.ning.http.client.AsyncHttpClient.requestBuilder(AsyncHttpClient.java:586) ~[otp.jar:1.1]
        at com.ning.http.client.AsyncHttpClient.prepareGet(AsyncHttpClient.java:412) ~[otp.jar:1.1]
        at org.opentripplanner.updater.stoptime.WebsocketGtfsRealtimeUpdater.run(WebsocketGtfsRealtimeUpdater.java:132) ~[otp.jar:1.1]
        at org.opentripplanner.updater.GraphUpdaterManager$1.run(GraphUpdaterManager.java:148) [otp.jar:1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
16:46:09.758 ERROR (TripTimes.java:315) Negative running time in TripTimes after stop index 22.
16:46:09.758 ERROR (Timetable.java:505) TripTimes are non-increasing after applying GTFS-RT delay propagation to trip 8466586.
16:46:09.759 WARN (TimetableSnapshotSource.java:260) Failed to apply TripUpdate.
16:46:09.766 ERROR (TripTimes.java:315) Negative running time in TripTimes after stop index 69.
16:46:09.766 ERROR (Timetable.java:505) TripTimes are non-increasing after applying GTFS-RT delay propagation to trip 8458240.
16:46:09.766 WARN (TimetableSnapshotSource.java:260) Failed to apply TripUpdate.
......
16:46:09.911 ERROR (Timetable.java:505) TripTimes are non-increasing after applying GTFS-RT delay propagation to trip 8457995.
16:46:09.911 WARN (TimetableSnapshotSource.java:260) Failed to apply TripUpdate.
16:46:09.912 WARN (TimetableSnapshotSource.java:837) MODIFIED trip doesn't have a start date in TripDescriptor, skipping.
16:46:09.912 WARN (TimetableSnapshotSource.java:260) Failed to apply TripUpdate.
16:46:10.806 WARN (PropertiesHelper.java:330) There is no way how to transform value "true" [java.lang.Boolean] to type [java.lang.String].
16:46:10.877 ERROR (OTPMain.java:169) An uncaught OutOfMemoryError occurred inside OTP. Restarting server.
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method) ~[na:1.8.0_92]
        at java.lang.Thread.start(Thread.java:714) ~[na:1.8.0_92]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool.startWorker(AbstractThreadPool.java:184) ~[otp.jar:1.1]
        at org.glassfish.grizzly.threadpool.SyncThreadPool.startWorker(SyncThreadPool.java:131) ~[otp.jar:1.1]
        at org.glassfish.grizzly.threadpool.SyncThreadPool.<init>(SyncThreadPool.java:83) ~[otp.jar:1.1]
        at org.glassfish.grizzly.threadpool.GrizzlyExecutorService.setImpl(GrizzlyExecutorService.java:104) ~[otp.jar:1.1]
        at org.glassfish.grizzly.threadpool.GrizzlyExecutorService.<init>(GrizzlyExecutorService.java:82) ~[otp.jar:1.1]
        at org.glassfish.grizzly.threadpool.GrizzlyExecutorService.createInstance(GrizzlyExecutorService.java:78) ~[otp.jar:1.1]
        at org.glassfish.grizzly.nio.NIOTransport.start(NIOTransport.java:478) ~[otp.jar:1.1]
        at org.glassfish.grizzly.http.server.NetworkListener.start(NetworkListener.java:745) ~[otp.jar:1.1]
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:278) ~[otp.jar:1.1]
        at org.opentripplanner.standalone.GrizzlyServer.run(GrizzlyServer.java:143) ~[otp.jar:1.1]
        at org.opentripplanner.standalone.OTPMain.run(OTPMain.java:166) [otp.jar:1.1]
        at org.opentripplanner.standalone.OTPMain.main(OTPMain.java:86) [otp.jar:1.1]
16:46:10.877 INFO (GrizzlyServer.java:67) Starting OTP Grizzly server on ports 51315 (HTTP) and 51311 (HTTPS) of interface 0.0.0.0
16:46:10.877 INFO (GrizzlyServer.java:69) OTP server base path is /var/otp
16:46:10.878 INFO (GrizzlyServer.java:49) Java reports that this machine has 24 available processors.
16:46:10.878 INFO (GrizzlyServer.java:57) Maximum HTTP handler thread pool size will be 24 threads.
16:46:11.185 WARN (PropertiesHelper.java:330) There is no way how to transform value "true" [java.lang.Boolean] to type [java.lang.String].
16:46:11.187 ERROR (OTPMain.java:169) An uncaught OutOfMemoryError occurred inside OTP. Restarting server.
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method) ~[na:1.8.0_92]
        at java.lang.Thread.start(Thread.java:714) ~[na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950) ~[na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1368) ~[na:1.8.0_92]
        at org.glassfish.grizzly.utils.DelayedExecutor.start(DelayedExecutor.java:88) ~[otp.jar:1.1]
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:266) ~[otp.jar:1.1]
        at org.opentripplanner.standalone.GrizzlyServer.run(GrizzlyServer.java:143) ~[otp.jar:1.1]
        at org.opentripplanner.standalone.OTPMain.run(OTPMain.java:166) [otp.jar:1.1]
        at org.opentripplanner.standalone.OTPMain.main(OTPMain.java:86) [otp.jar:1.1]
16:46:11.187 INFO (GrizzlyServer.java:67) Starting OTP Grizzly server on ports 51315 (HTTP) and 51311 (HTTPS) of interface 0.0.0.0
16:46:11.187 INFO (GrizzlyServer.java:69) OTP server base path is /var/otp
16:46:11.187 INFO (GrizzlyServer.java:49) Java reports that this machine has 24 available processors.
16:46:11.187 INFO (GrizzlyServer.java:57) Maximum HTTP handler thread pool size will be 24 threads.
16:46:11.380 WARN (PropertiesHelper.java:330) There is no way how to transform value "true" [java.lang.Boolean] to type [java.lang.String].
16:46:11.382 ERROR (OTPMain.java:169) An uncaught OutOfMemoryError occurred inside OTP. Restarting server.
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method) ~[na:1.8.0_92]
        at java.lang.Thread.start(Thread.java:714) ~[na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950) ~[na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1368) ~[na:1.8.0_92]
        at org.glassfish.grizzly.utils.DelayedExecutor.start(DelayedExecutor.java:88) ~[otp.jar:1.1]
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:266) ~[otp.jar:1.1]
        at org.opentripplanner.standalone.GrizzlyServer.run(GrizzlyServer.java:143) ~[otp.jar:1.1]
        at org.opentripplanner.standalone.OTPMain.run(OTPMain.java:166) [otp.jar:1.1]
......
```

Just gets into an infinite loop of server restarts at this point...

**Comment by fpurcell** [comment]
I'm going to play around with some other config files, and see if I have any more success ... going to remove a lot of configs that are in there for RT updates, etc....

**Comment by fpurcell** [comment]
this turned out to be a server config issue, and nothing to do with MOD OTP
